### PR TITLE
Extract the version from the latest commit hash

### PR DESCRIPTION
**Pull request by hectorj2f**
In order to fix the master build http://jenkins.cd.k8s.fabric8.io/job/fabric8-ui/job/fabric8-ui-openshift-nginx/job/master/4/console. 

ping @rawlingsj for review

### CODE REVIEW

**Comment by fabric8cd** [comment]
@hectorj2f snapshot fabric8-ui-openshift-nginx image is available for testing.  `docker pull fabric8/fabric8-openshift-nginx:SNAPSHOT-PR-12-1`

**Comment by jstrachan** [comment]
where is `getNewVersion{}` defined?

**Comment by hectorj2f** [comment]
@jstrachan isn't here https://github.com/fabric8io/fabric8-pipeline-library/blob/master/vars/getNewVersion.groovy ? I believe it should be included

**Comment by jstrachan** [comment]
LGTM

**Pull request merged**
